vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|02 Nov 2007 07:54:21 -0000
vti_extenderversion:SR|5.0.2.6790
vti_lineageid:SR|{A196B752-94E1-4572-9139-B718510861AD}
vti_backlinkinfo:VX|Nick/skating/SnakeSessions.asp
vti_cacheddtm:TX|02 Nov 2007 07:54:21 -0000
vti_filesize:IR|3300
vti_cachedbodystyle:SR|<body>
vti_cachedlinkinfo:VX|Q|stylesheets\\\\dallett.css A|searchresults.asp H|http://snake.kittycrack.net
vti_cachedsvcrellinks:VX|NQUS|/Nick/skating/stylesheets\\\\dallett.css FAUS|Nick/skating/searchresults.asp NHHS|http://snake.kittycrack.net
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|windows-1252
